export const GET_DOGS = 'GET_DOGS';
export const SEARCH_DOGS_BY_NAME = 'SEARCH_DOGS_BY_NAME';
export const FILTER_BY_TEMPERAMENTS = 'FILTER_BY_TEMPERAMENTS'
export const POST_DOG = 'POST_DOG'
export const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMNETS'
export const GET_DOG_BY_ID = "GET_DOG_BY_ID"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"